### ISSUE TITLE
Broadcast resized stop after animation completes

### ISSUE THREAD

**Issue by rjbriody** [ManifestWebDesign/angular-gridster#110]
Hello.

I am rendering a canvas inside a gridster item. I am having difficulty keeping the dimensions of the canvas sync'd w/ the gridster item. The problem seems to be that the gridster item's dimensions continue to change as the box goes through the "animated snap to grid" process.

Here is what I see happening:
- resize events are fired as gridster item is resized
- stop event is fired on mouse up.
- item continues to resize during animation as it snaps to grid.

and at this point my canvas is out of sync w/ the gridster item because I haven't received any event(s) corresponding to the final (post-animation) width and height.

Perhaps the "resized stop" event should not be broadcast until animation is complete? Maybe there should be a separate event for "resize complete"? Maybe there is a clean way to handle this that I just don't know about. 

Quick notes: 
Attempting to manually watch the dimensions of the parent element also results in the same issue. I would be OK w/ disabling animation as a workaround. If this is possible, please let me know.

**Comment by maximou4391** [comment]
Hi @szabyg did you find a solution to render something even when the transition is not ended? To have a more fluid animation.

Thanks a lot.
