### ISSUE TITLE
Dynamic HTML Passing into GridsterItem

### ISSUE THREAD

**Issue by britztopher** [ManifestWebDesign/angular-gridster#115]
I am currently trying to add content/html when a widget is created, however, it seems like you need to have the HTML defined already within the gridsterItem directive.  I am currently working on functionality that would allow the gridster to take an HTML template file and use that to insert it as content. For example, right now if you were to loop through a bunch of widgets to be created they all would get the same HTML because its defined directly in the HTML.  It would be nice to have a way to create a generic gridsterItem container that could hold whatever HTML you want to pass it.  

Any ideas/suggestions/comments on this @danomatic ?

I was thinking upon initial creation of a grid item we could pass in a template.  For example, 

``` javascript

 widgets:[
                        {col: 0, row:0, name:'Plan'},
                        {col: 2, row:1, name:'Learn', template: '<h1>Hello World</h1>'}
                    ]

```

**Comment by Cristianopavan** [comment]
<div ng-widget>
<div gridster >
<ul>
<li gridster-item="item"  ng-repeat="item in widget" >
	 <div id="header"    ng-show="myVar" >income</div>  
 <div class="panel-body "   ng-style = "myStyle">
	<h1  class="title" ; " ng-show="myTitle">widget chart</h1>
	<i class="fa fa-dollar"   style="font-weight:lighter" ng-show="myDollar" ></i>{{message}}</div>
	 <span id="rightcorner" ng-show="rightcorner"><i class="fa fa-level-up"></i>67577</span>
	 
</li></ul>
</div> 



<script>
 var chart=angular.module('test', ['gridster'])
 chart.directive('ngWidget',function ()
{
    return {
        restrict: "ECA",        
        templateURl: 'C:xampp/htdocs/grid/index.html'\,

		link:function($scope){
			$scope.widget=	[
			{
			sizeX:3,
			sizeY:3,
		   row:0,
            col:0	   
			},
			{
			sizeX:2,
			sizeY:4,
		   row:0,
            col:5
				
			}];
		}



}
});
</script>


this is  my code now i just want to pass an array an directive and it should be reflected in the gridster can u please help me out with this . Thanks i m new to angular if i m wrong please lemme know
