### ISSUE TITLE
Replacing jQuery UI draggable removed automatic scrolling on drag

### ISSUE THREAD

**Issue by danomatic** [ManifestWebDesign/angular-gridster#128]
jQuery UI automatically scrolls the browser window when dragging over the top and bottom of the page.  The draggable resizable rewrite removed this.  It should be brought back.

**Comment by jameswyse** [comment]
I'm still having issues with this - it doesn't scroll when gridster is inside a scrollable container (eg a fixed height div with `overflow-y: scroll`)

**Comment by rahulbhadhoriya** [comment]
did anyone solve it?
