### ISSUE TITLE
Access gridster options (from directive)

### ISSUE THREAD

**Issue by sonoman** [ManifestWebDesign/angular-gridster#160]
Hey:

I'm wrapping your directive in a directive of mine (because I'm combining with another directive that provides app isolation), and I'm trying to implement "maximize" behavior, and I was wondering what would be the best way to access the options after being merged with the default gridster options (i think that happens in the "gridster" directive controller)

**Comment by danomatic** [comment]
Also, the latest version exposes the gridster and gridsterItem controllers in their scopes
