### ISSUE TITLE
Add 'throttleWindowResizeCalls' (or similar) to the config options to delay window.resize() firing

### ISSUE THREAD

**Issue by key10** [ManifestWebDesign/angular-gridster#171]
I was looking through your demo and the source code, and it seems to be working well. However, I think adding the ability to set a debounce time to the window.resize function would allow for each dev to achieve their own speed:responsiveness ratio that he/she desires. 

Just a thought, so I wanted to share. 

Thoughts?

EDIT: I believe that a 'throttle' would be better in this case. I have looked into the differences between 'debounce' and 'throttle', and throttling the window.resize() calls is more along the lines of what I had in mind. This website has a good explanation and demo of the difference: http://drupalmotion.com/article/debounce-and-throttle-visual-explanation

@danomatic : The lodash.js library provides the throttle functionality, but would it be acceptable to make lodash a dependency of the angular-gridster project?

**Comment by danomatic** [comment]
Latest version debounces, but does not provide a throttle option.  If a specific frequency rate is needed, we can add the option pretty easily.
