### ISSUE TITLE
NPM published version is obsolete

### ISSUE THREAD

**Issue by huston007** [ManifestWebDesign/angular-gridster#206]
Please update it.

**Comment by eouin** [comment]
Please update NPM

**Comment by danomatic** [comment]
Can someone submit a PR?  I'm in meeting the rest of the day!

**Comment by huston007** [comment]
@danomatic with pleasure but have no npm credentials :)

**Comment by mkusher** [comment]
any updates? I still unable to install angular-gridster via npm

**Comment by danomatic** [comment]
done
