### ISSUE TITLE
Element moves left 1 col on resize

### ISSUE THREAD

**Issue by stefan-1st** [ManifestWebDesign/angular-gridster#208]
This might be related to #130 

Following situation:
i have a grid with 6 rows with a width of 853 pixels overall (142.16666... per column). If i resize an element lets say south it is moved to the left by one column. This is due to the calculation of the pixelsToColumns() method. (colWidth is auto, width is auto)

Eg. original column is 3 (426px) => Math.floor(426 / 142.16666...) => Math.floor(2.9964...) => 2

Perhaps it would be good to floor the curColWidth as well. Problem that i see with this solution is that in some situations the columns would not use the full width.

**Comment by barretodavid** [comment]
Yes, it's happening to me too. When I try to resize an item to the right, the element tries to move to the left column. The only way to stop this behavior is to set "outerMargin: true" in the configuration object but that in turn is messing my layout.

**Comment by danomatic** [comment]
Thank you for reporting this.  How can I reproduce this?  Are you using the latest version?  I'm not experiencing this in the demo.

**Comment by stefan-1st** [comment]
Set up a plunker.

http://embed.plnkr.co/Y4wJHwx6AVJ08tfZLqTj/

Checked in Firefox and Chrome. If you grab a handle and resize a cell it automatically expands to the left by one.

**Comment by danomatic** [comment]
Thank you!  This is fixed in the latest version.
