### ISSUE TITLE
NPM Version won't install !!! Can you please update

### ISSUE THREAD

**Issue by eouin** [ManifestWebDesign/angular-gridster#210]
> angular-gridster@0.10.0 install /node_modules/angular-gridster
> node ./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update

module.js:340
    throw err;
          ^
Error: Cannot find module '/node_modules/angular-gridster/node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by danomatic** [comment]
NPM version is updated.  Do I still need to change anything?
