### ISSUE TITLE
Wrong positions restoring on angular 1.3

### ISSUE THREAD

**Issue by huston007** [ManifestWebDesign/angular-gridster#214]
I have configuration like that:
```
$scope.standardItems = [
      { sizeX: 1, sizeY: 1, row: 1, col: 0 },
      { sizeX: 1, sizeY: 1, row: 0, col: 0 },
];
```
But after update angular to 1.3 it wont be placed correctly: first item became top, and second is bottom

**Comment by huston007** [comment]
I tried to add zero $timeout to wait for items placing finish and it's works. Is there some cons?

**Comment by huston007** [comment]
Uh, $timeout made widgets placing delayed.
As an workaround, set gridsterOptions to false first, and then do
```
$timeout(function () {
     $scope.gridsterOptions.floating = true;
});
```
after gridster data array is loaded

**Comment by jonathanherdt** [comment]
I have the same problem and am using Ionic Beta 14. The timeout fix didn't work for me. What did work, though, was disabling caching for the view in question, as described [here](http://ionicframework.com/docs/api/directive/ionNavView/). I simply used

```html
  <data-ion-view cache-view="false">
```

**Comment by danomatic** [comment]
The current best solution is to sort the items:

```javascript
$scope.standardItems.sort(function(a, b) {
	var n = a.row - b.row;
	if (n !== 0) {
		return n;
	}
	return a.col - b.col;
})
```

Since items add themselves to the gridster directly, the gridster controller adds each one and floats on an individual basis.  A timeout may solve the issue but it probably needs to be in a different place.

**Comment by danomatic** [comment]
Anyone who can, please try latest master.  https://github.com/ManifestWebDesign/angular-gridster/commit/8d703d434c2b7035098b427eee8e43703fe0f7f5 .   It might solve this issue.  I centralized all the calls to floatItemsUp so that the items aren't directly calling it as they set their position.  If that doesn't work, we could possibly add a delay to the watch that calls floatItemsUp to ensure all the items have a chance to place themselves in the grid.

**Comment by danomatic** [comment]
...don't use master for production yet.

**Comment by huston007** [comment]
https://github.com/ManifestWebDesign/angular-gridster/commit/8d703d434c2b7035098b427eee8e43703fe0f7f5 works for me, thanks!

**Comment by danomatic** [comment]
Beware I think it introduced some other bugs, so we're headed in the right direction, but it isn't production ready.

**Comment by huston007** [comment]
I'll try to use that version and to test it. Issue looks solved
