### ISSUE TITLE
Question: readme.md does not mention module name to include

### ISSUE THREAD

**Issue by michahell** [ManifestWebDesign/angular-gridster#219]
I do not know if it is common knowledge how to include angular modules by name,
but how i usually approach this is to open demo's and see what the module / directive name is that is included, in this case simply ```gridster```. Might it be neccesary to include this in the readme or not? if not, i assume that any angular directive or module named angular - < name > should be included in your angular app by including ```<name>```.

Oh, and GREAT addon! Thanks a bunch, really came in handy :D

**Comment by danomatic** [comment]
Thanks!  This has been added to the latest commit.
