### ISSUE TITLE
Auto-resize gridster-item when content within is resized

### ISSUE THREAD

**Issue by manastalukdar** [ManifestWebDesign/angular-gridster#220]
I have accordions within each gridster item. When I expand those accordions, the gridster item doesn't also expand, unless the items are currently stacked vertically, i.e, when I re-size the browser window to a very low width to simulate a mobile device. Is there any way to accomplish this at all browser widths?

**Comment by huston007** [comment]
@manastalukdar Sorry, but it looks like you use wrong thing for your needs - gridster is about grid. I can suggest you to use another component like https://github.com/davidjnelson/angular-accordion to cover your needs.

**Comment by manastalukdar** [comment]
@huston007 So is a gridster-item meant to be populated only with content of static size?

**Comment by huston007** [comment]
@manastalukdar no, the scroll is adding when widget content is huge than widget size. But widget size is  wired to grid size.

**Comment by manastalukdar** [comment]
@huston007 "But widget size is wired to grid size.", this is very important information. Thanks. I think if I dynamically change the widget size based on the new size of the content within, I should be able to solve the problem. What does 1 (the widget size unit) represent in terms of pixels? Is that always uniform?

**Comment by danomatic** [comment]
See the documentation for "rowHeight" in the readme.  If it's set to an integer, each unit represents that many pixels.  If it is "match", the height matches the "colWidth"

**Comment by manastalukdar** [comment]
I was able to resolve the issue by dynamically changing the widget size based on the new size of the content within.

**Comment by nikhil-venkat** [comment]
Hey @manastalukdar Can you share more details on  how you ended up resolving this issue ?

**Comment by manastalukdar** [comment]
@nikhil-venkat I have an angular directive where I track if the height of the widget changes. If so, then I fire an event that sets sizeY to a new value.

**Comment by bigdatamoore** [comment]
Hi @manastalukdar, could you share an snippet of your code or directive where you did this?  We are facing a similar challenge.  Thanks

**Comment by bobpr01** [comment]
Hi @manastalukdar Could you please share your angular direcitve to track the height of widget

**Comment by enesaltinok** [comment]
This one works for me:

Html
```
<div gridster>
    <ul>
        <li gridster-item="item" ng-repeat="item in standardItems">
            <div gridster-dynamic-height item="item"></div>
        </li>
    </ul>
</div>
```
Angularjs

```javascript

angular.module('app.core').directive('gridsterDynamicHeight', gridsterDynamicHeight);
	
	gridsterDynamicHeight.$inject = [];
	function gridsterDynamicHeight(){
		
		var directive = {
			scope: {
	            item: "=" //gridster item
	        },
			link: link,
	        restrict: 'A'
	    };
		return directive;
		
		function link(scope, element, attrs) {
			
			scope.$watch(function() {
				
            	return element[0].scrollHeight;
            },
            function(newVal, oldVal) { 
            	
            	var rowHeightOption = 75; // Change this value with your own rowHeight option
            	var height = rowHeightOption * scope.item.sizeY;
            	if(newVal > height){
            		            	
            		var div = Math.floor(newVal / rowHeightOption);
            		div++;
            		scope.item.sizeY = div; 
            	}
            });
		}
	}
```

**Comment by pedro-mass** [comment]
@enesaltinok -> your solution mostly worked for me, but not on the last sizeY update. 
For some reason, I see that the code is updating scope.item.sizeY but it's not actually updating the scope.
I thought it was a digest issue, but my attempts to get it working has failed.
