### ISSUE TITLE
Scoll on overflow

### ISSUE THREAD

**Issue by abigail1000** [ManifestWebDesign/angular-gridster#222]
I could be overlooking something totally obvious, but I can't seem to get an inner scrolling div working on a gridster item. I've tried setting the overflow on the div containing the content (what would be the "box-content" class in the dashboard example) and tried wrapping the content inside an inner div.  Either way I get no scrollbars and overflowing content.  If I set overflow to auto on the outer container (the "box" class) I get scrollbars but they appear within the resize handle zone (ok if I remove the south and east handles but I'd rather not.)  Ideally the scrollbars would be offset with padding on the left and bottom, but setting overflow on anything inside the box class just isn't working for me.  Do you have a working example I could follow?  
Other than that I have had no issues and these are perfect for what I need, thanks for the awesome work!

**Comment by danomatic** [comment]
The gridster items are position:absolute.  One way to make an inner element fill the gridster item is to use a style like this:

```css
.gridster-item .inner-item {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  padding: 10px;
}

```

**Comment by abigail1000** [comment]
position:absolute is what I was missing.  Thank you!
