### ISSUE TITLE
Remove a grid widget

### ISSUE THREAD

**Issue by psurya** [ManifestWebDesign/angular-gridster#224]
Hi,

It would be really nice to have an option to remove a widget.

Currently I am splicing out the item, and it distorts the entire layout. the gridster properties are being randomly assigned to next iterated item.

**Comment by danomatic** [comment]
Something is not tight with the setup or there is a subtle bug that you've tickled.  If you use ng- repeat, it should work automatically.  Can you provide an example?

**Comment by SunJieMing** [comment]
I have the same issue.

**Comment by danomatic** [comment]
I need to see an example of this to troubleshoot.  If you are using something like track by $index and you don't have any binding of row and col, then perhaps that is causing this for you.
