### ISSUE TITLE
Ability to flip the whole gridster item

### ISSUE THREAD

**Issue by psykidellic** [ManifestWebDesign/angular-gridster#226]
I am trying to use https://github.com/lemming/angular-flip or similar libraries. The problem is that this lets only the content to flip and not the whole gridster item.

Is that even possible by doing some hacks? I have tried adding the same style to the gridster items without any effect.

Any suggestions how I can even approach the problem?

**Comment by danomatic** [comment]
What element are you putting it on?  If you put it on the gridster-item, it should work.  However the flip directive is probably flipping the elements inside the gridster-item, so you probably will want to clear the backround color on the gridster-item in the css: background: none.  Then you can add the background color to the elements inside the gridster item.
