### ISSUE TITLE
Rounding error with resize

### ISSUE THREAD

**Issue by Pouja** [ManifestWebDesign/angular-gridster#230]
Reproduce:
1. Take the example in demo/main
2. Change the margins of 'Standard Items' below 20
3. You will see that when you change the width of an item, it will shift the item one place to the left.

This is due the calculation of curColWidth in the refresh function of the directive gridster. 
Not sure what the perfect solution will be, but I tried to round the ```curColWidth``` with ```Math.round```. With that it works like intended. But I'm not sure if that is the perfect solution.

**Comment by danomatic** [comment]
I'm not able to reproduce on the latest version.  Is this still an issue for you?

**Comment by Pouja** [comment]
Seems not anymore :). Closing it.
