### ISSUE TITLE
Draggable.handle dont work

### ISSUE THREAD

**Issue by tjet-lw** [ManifestWebDesign/angular-gridster#232]
Its not possbile to resign draggable handle class, the whole widget is always draggable form everywhere and if I set draggeble:{
handle: 'h3'
}

should only make the H3 draggable but nothing happens, I can drag the widget from everywhere

**Comment by tjet-lw** [comment]
Found the problem myself, was using a ng-include for rendering my widgets and ng-include does not replace the html so my draggable class could not be found and angular-gridsters fallback when not finding the handle class is to set the whole element.

Work around if any others may have the same problem is to create a custom directive like so:
app.directive('customWidget', function () {
  return {
    restrict: 'E',
    templateUrl: './views/partials/widget.html',
    replace: true //Very important
  }
});

**Comment by mikehaas763** [comment]
I think there is a root problem relating to this because of templateUrl being fetched async. I'll open another issue to track it. Also, the replace property is being deprecated so it doesn't make sense to use it for a solution. Although, it didn't work for me anyways.
