### ISSUE TITLE
Dealing with $resource object

### ISSUE THREAD

**Issue by maxailloud** [ManifestWebDesign/angular-gridster#234]
Hello everyone,

I'm currently using this library to make a dashboard project, I mean not exactly a dashboard but almost the same as the [dashboard demo](https://rawgit.com/ManifestWebDesign/angular-gridster/master/index.html#/dashboard) so you can see the point.
And by the way thanks for the lib it's really amazing.

My widget are all [$resource](https://docs.angularjs.org/api/ngResource/service/$resource) extended object. 
So when I update a widget I can call the $update method on it and I'm done updating it.

The library work just fine, but just for one drag and drop. After I got this error:
 > Uncaught TypeError: Cannot read property 'putItem' of null angular-gridster.js:1081 

And the related trace:
 > angular.module.constant.controller.directive.controller.setPosition angular-gridster.js:1081 
dragStop angular-gridster.js:1446 
mouseUp angular-gridster.js:1343 
angular.module.constant.controller.unifiedInput.doEvent angular-gridster.js:696

Maybe the fact that when we call a $save/$update method on a object something is changed inside of it and angular-gridster can figure out how to deal with this object anymore. Really don't know.

**Comment by maxailloud** [comment]
And by the way I'm using the lastest version, the v0.11.7.

**Comment by maxailloud** [comment]
With my widget being an angular $resource as gridster item I guess the issue is about that.
When saving/updating my widget its content is updated by the API return.

Because of that, I think, the [`$destroy` event](https://github.com/ManifestWebDesign/angular-gridster/blob/master/src/angular-gridster.js#L1979) is catch by the [`gridsterItem` directive ](https://github.com/ManifestWebDesign/angular-gridster/blob/master/src/angular-gridster.js#L1829).

I think this event is the reason why the [`this.gridster` object](https://github.com/ManifestWebDesign/angular-gridster/blob/master/src/angular-gridster.js#L1081) in the  [`GridsterItemCtrl` controller](https://github.com/ManifestWebDesign/angular-gridster/blob/master/src/angular-gridster.js#L1034) is null. 

Is there a solution?

**Comment by maxailloud** [comment]
A little up.
Is there something I can do to make it work?

**Comment by maxailloud** [comment]
I resolved this issue by using `track by` option to ngRepeat directive.

**Comment by jziggas** [comment]
Thanks @maxailloud I just ran into the same or a similar issue due to live refresh of widgets and adding `track by $index` seems to have resolved it.
