### ISSUE TITLE
Resize/Drag problems using maxRows

### ISSUE THREAD

**Issue by sosoriov** [ManifestWebDesign/angular-gridster#236]
I am trying to use the maxRows option but when I apply it the widgets "get crazy". I cannot say an error pattern, it always does something different. You can check the issue in the following link: http://screencast.com/t/33wAwDXFWAm2

Other example: 
http://screencast.com/t/9ngUgpM9

Any idea how can I solve this issue? 

ps: I'm using maxRows : 34 in my configuration

**Comment by andreabadesso** [comment]
+1 I have the same issue

**Comment by danomatic** [comment]
Thank you for reporting this. I believe it is an issue with the code trying to keep the widget inside the bounds, so it's adjusting the rows to allow for the newer height. Are you still having this problem with the latest release?

**Comment by bergben** [comment]
Hi, I am having kind of the same issue.

Using the latest release 0.13.2:
With the following configuration there seems to be a bug where an item can be placed on top of another item. The bug is created when you try to place an item in a column where there is already another item close to the bottom limit. 

Furthermore I wanted to ask if there is really no possibility to give the columns and rows a border / styling?

Thank you!

     $scope.standardItems = [
              { sizeX: 1, sizeY: 1, row: 0, col: 0 },
              { sizeX: 1, sizeY: 2, row: 0, col: 2 },
              { sizeX: 1, sizeY: 3, row: 0, col: 4 },
              { sizeX: 1, sizeY: 6, row: 0, col: 5 },
              { sizeX: 1, sizeY: 5, row: 1, col: 0 },
        ];

        $scope.gridsterOpts = {
            columns: 6, // the width of the grid, in columns
            pushing: false, // whether to push other items out of the way on move or resize
            floating: false, // whether to automatically float items up so they stack (you can temporarily disable if you are adding unsorted items with ng-repeat)
            swapping: false, // whether or not to have items of the same size switch places instead of pushing down if they are the same size
            width: 'auto', // can be an integer or 'auto'. 'auto' scales gridster to be the full width of its containing element
            colWidth: '100', // can be an integer or 'auto'.  'auto' uses the pixel width of the element divided by 'columns'
            rowHeight: '30', // can be an integer or 'match'.  Match uses the colWidth, giving you square widgets.
            margins: [4, 4], // the pixel distance between each widget
            outerMargin: true, // whether margins apply to outer edges of the grid
            isMobile: false, // stacks the grid items if true
            mobileBreakPoint: 200, // if the screen is not wider that this, remove the grid layout and stack the items
            mobileModeEnabled: false, // whether or not to toggle mobile mode when screen width is less than mobileBreakPoint
            minColumns: 1, // the minimum columns the grid must have
            minRows: 2, // the minimum height of the grid, in rows
            maxRows:8,
            defaultSizeX: 1, // the default width of a gridster item, if not specifed
            defaultSizeY: 1, // the default height of a gridster item, if not specified
            minSizeX: 1, // minimum column width of an item
            maxSizeX: null, // maximum column width of an item
            minSizeY: 1, // minumum row height of an item
            maxSizeY: null, // maximum row height of an item
            resizable: {
                enabled: false,
                handles: ['n', 'e', 's', 'w', 'ne', 'se', 'sw', 'nw'],
                start: function (event, $element, widget) { }, // optional callback fired when resize is started,
                resize: function (event, $element, widget) { }, // optional callback fired when item is resized,
                stop: function (event, $element, widget) { } // optional callback fired when item is finished resizing
            },
            draggable: {
                enabled: true, // whether dragging items is supported
                handle: '.my-class', // optional selector for resize handle
                start: function (event, $element, widget) { }, // optional callback fired when drag is started,
                drag: function (event, $element, widget) { }, // optional callback fired when item is moved,
                stop: function (event, $element, widget) { } // optional callback fired when item is finished dragging
            }
        };

**Comment by andreabadesso** [comment]
I'm still having the issue with the latest version, hard to reproduce tho!
![overlap-1](https://cloud.githubusercontent.com/assets/3586068/7349045/a09df266-eccc-11e4-8dec-419a99f67160.png)
![overlap-2](https://cloud.githubusercontent.com/assets/3586068/7349046/a0a28844-eccc-11e4-9ada-78bfa8ccb81d.png)

**Comment by samueljun** [comment]
Hey guys, here is a JSFiddle that shows off what I'm seeing: http://jsfiddle.net/s3229t77/.

Here I'm using floating = false and pushing = false.

**Comment by bergben** [comment]
Hey guys, as you can see above I tried to fix the bugs. I was actually able to do so and introduced some more functionalities like the fixRows config parameter which sets the height of gridster fixed to the amount of maxRows. I also created a pull request.
You are welcome to try if my fork fixes your bugs as well!

**Comment by samueljun** [comment]
+1 

@bergben's commit (seen here [jsfiddle](http://jsfiddle.net/cwwwk58m/3/)) solves the issue I'm seeing when compared to the current release version (seen here [jsfiddle](http://jsfiddle.net/s3229t77/)).

**Comment by danomatic** [comment]
I played with the fiddles and noticed that they both have issues if pushing and floating are enabled, but the other behavior seems to be a little better.  I don't have time to thoroughly test this.  How confident are you that this doesn't introduce unexpected regressions?

**Comment by bergben** [comment]
I'll test it in more detail and get back to you then!

**Comment by bergben** [comment]
As promised I made further tests and updates. There have indeed been problems with float and pushing enabled. I fixed that and also introduced some other functionalities. I tested everything and it seemed to work. Please be my guest to test the changes yourself. I opened a new pull request for my changes, which also include the ability to style the gridster's columns and rows.
