### ISSUE TITLE
Ignore selector for dragable

### ISSUE THREAD

**Issue by huston007** [ManifestWebDesign/angular-gridster#237]
Now it is impossible to specify some selector inside draggable handle which shouldn't be draggable - links, buttons for example.
If we added draggable.ignore param to gridster config, it would be great!

**Comment by danomatic** [comment]
Just use the :not selector:

```js
	draggable: {
		enabled: false,
		handle: '.drag-handle:not(.some-class)'
	},
```

**Comment by huston007** [comment]
So, actually I can use something like handle: `.drag-gandle *:not(.some-class)` but it looks like a low selector in case of performance, isn't it?

**Comment by danomatic** [comment]
depending on what you need, it could be `.drag-handle, *:not(.some-class)`

**Comment by huston007** [comment]
@danomatic hm, you're right. Just as simple as it is. Thank you)
