### ISSUE TITLE
ResizeHandle doesn't update its minHeight and minWidth

### ISSUE THREAD

**Issue by nikek** [ManifestWebDesign/angular-gridster#243]
I'm using the grid with width:auto (which works awesomely btw) but have a problem with resizing my items after I've resized the window or changed column count.

The items' minHeight and minWidth are keeping their initial values in the ResizeHandle. This leads to the inability to resizing an item to for example height 200 when initial minHeight was 300 and still is. On mouse up the item instead just grows to the size of two columns and two rows because minHeight/minWidth is larger than column width and row height.

**Comment by nikek** [comment]
Holy sheet, It's already solved! I was just on an old version! Way to go!

**Comment by danomatic** [comment]
Glad it worked!
