### ISSUE TITLE
Upgrading to newer version - cant get dragging to work

### ISSUE THREAD

**Issue by PoOoZaQ** [ManifestWebDesign/angular-gridster#247]
I've upgraded today from a version I took in the beginning of the month, and I can't get the dragging to work.
It works fine if I return to the older version.

Old Version: http://pastebin.com/5pQs1Fqz

I've minimized my settings to be as default as I could (works in the older version):
http://pastebin.com/2pkuX28i

Any help will be appreciated..

Thanks

**Comment by danomatic** [comment]
This is fixed on latests master.  I will make a new release tag soon.
