### ISSUE TITLE
Draggability broken in Dashboard demo

### ISSUE THREAD

**Issue by amergin** [ManifestWebDesign/angular-gridster#248]
Seems that the draggability feature is broken on the demo page: https://rawgit.com/ManifestWebDesign/angular-gridster/master/index.html#/dashboard. Main demo works okay.

**Comment by amergin** [comment]
I seem to have the same issue in my app when I use master. Commit https://github.com/ManifestWebDesign/angular-gridster/commit/425ef5286d5e3560b6f4444bab661630dd26c86e breaks the functionality for me. The commit before it works okay. @twolff-iow, any idea what could cause this?

**Comment by danomatic** [comment]
This is fixed on the latest master.  I will make a new release soon.
