### ISSUE TITLE
Gridster Provider

### ISSUE THREAD

**Issue by TiagoBraga39** [ManifestWebDesign/angular-gridster#249]
Hi, ready for a huge text? :D 
I think this is a must have.

First of all, thank you a lot for your contribution on angular-gridster!

I was thinking if it was possible  for you to add a simple provider on the gridster file.
<b>Reason:</b> access to gridster environment (functions) from outside, without having to create a directive that will require gridster. (The only way possible until today i guess)

Instead of creating the directive and on compile function do:

```javascript
angular.module('MyAwesomeModule').directive('MyAwesomeDirective', function () {
        return {
            restrict: 'E',
            require: '^gridster',
            controller: function ($scope, $element, $attrs, $transclude) {
            },
            compile: function compile(tElement, tAttributes, $window, Gridster) {
                return {
                    pre: function preLink(scope, element, attributes) {  
                    },
                    post: function link(scope, element, attrs, Gridster) {
                        // Now i can access to Gridster by: Gridster.setOptions(awesomeObject)
                    }
                };
            }
        };
);
```

(I dont like this ^^)

-------
My thoughts
-------
Is it possible do add a provider on your gridster file as:
```javascript
angular.module('gridster', []).provider("gridsterProvider",function(){
	    this.$get = function () {
	        var publicMethods = {
	            setOptions: function (options) {
	                return 'setOptions method'; // Todo actually make it work :)
	            }
	        }
	        return publicMethods;
	    }
	})
```

So far i am working with this, so it would be awesome to access to the gridster environment from outside without having to create the directive.

using on a controller:
```javascript
$scope.fun1 = function () {
      console.log(gridsterProvider.setOptions());  // Prints 'setOptions method'
}
```

--------
Edit
--------
The amount of work you would need to do on your functions (on controller, for example):
```javascript
.controller('GridsterCtrl', ['gridsterConfig', '$timeout', 'gridsterProvider',
	function(gridsterConfig, $timeout, gridsterProvider) {
            gridsterProvider.gridsterConfig = gridsterConfig;
        }
```

And now we can access from the ouside:
```javascript
      gridsterProvider.setOptions(theNewOptions)); // now it changes
```

What do you think?

Awesome thanks :)
Tiago Braga

**Comment by amergin** [comment]
Not saying this wouldn't work, but would these be global default settings you are setting up in this way? There can be several instantiated grids in an application, how do identify which of them gets the options?

My motivation for having a callable Gridster service would be to able to trigger the layout algorithm in situations where the grid is sparse. In this case I would like the items to be re-aligned so that empty sections on the grid are filled.

**Comment by TiagoBraga39** [comment]
In some way that may be true. But then again we could just provide to the outside some methods, such as the next available position an item can ocuppy.
Or is there any way i can achieve without this?

Thanks,
Tiago Braga

**Comment by danomatic** [comment]
I looked at creating a provider and I believe it being a singleton that doesn't know about the scope would make that an unusable solution for many.  In the latest release I exposed the gridster and gridsterItem controllers to the scope so you can do what you want with them.  I hope that helps!
