### ISSUE TITLE
Listing a simple array of objects

### ISSUE THREAD

**Issue by shank8** [ManifestWebDesign/angular-gridster#252]
This may be available already, but I don't see the correct functionality by default.  If I want to use angular-gridster to just list a bunch of tiles using an array, then when the array gets updated/filtered gridster doesn't re-draw the elements from coordinate (0,0).  Instead the element stays in the exact same row/col as before.

For example, I have a search box that uses angular filter to filter the array.  I don't want to have to specify the row/col of the items, they should just go in order that they appear in the array. However, if I filter my array by a string, the elements that remain in the array also remain in the exact same position rather than getting re-drawn from (0,0).

**Comment by shank8** [comment]
I found a fix, but it is outside of the realm of angular-gridster so I am not sure if there is a way to fix it with the way the library is implemented currently.

Basically, I check whenever an item is added/removed from my array. Then I update the row and col manually based off of the index in the array.  This works, but it would be nice if this functionality was implemented into the library for when you don't want to have to manage the row/col yourself.
```
$scope.$watch('model.Users.filtered', function(newArr){
        var cols = $scope.defaultOpts['columns'];

        angular.forEach(newArr, function(user, ind){
            user.UI.row = Math.floor(ind/cols);
            user.UI.col = ind % cols;
        });
    });
```

**Comment by danomatic** [comment]
Items will automatically be placed wherever there is available space, top to bottom - but only if they don't have a row or col set.  The issue you are having is that once they are placed the first time, they get assigned a row and col and then that sticks.  Resetting those values is probably outside what the gridster directive should be controlling.  I like your solution.

**Comment by tabkram** [comment]
This is not a good Idea to handle "row" and "col" but myself. I think It very natural to manipulate assigned row and col by angular-gridster, specially if there is no need for the user to specify them.
