### ISSUE TITLE
Custom Drag Handle => match each element with class

### ISSUE THREAD

**Issue by jibap** [ManifestWebDesign/angular-gridster#253]
I suggest to get all element find with custom class 
(ex: widget with content and title bar with tools button, i need to not drag on tools , i add a div between tools and add custom class for dragging, and the same custom class on widget content).
![image](https://cloud.githubusercontent.com/assets/3915029/7027040/98b5272e-dd4d-11e4-93dc-d304e2a1a42d.png)

To fix it , use querySelectorAll: 
![image](https://cloud.githubusercontent.com/assets/3915029/7026935/0b3c94ae-dd4d-11e4-9854-65fc477572dc.png)

**Comment by danomatic** [comment]
It took a little more than that, but I just released a version that supports this:

https://github.com/ManifestWebDesign/angular-gridster/releases/tag/v0.13.1
