### ISSUE TITLE
Accessing the gridster object

### ISSUE THREAD

**Issue by mconner** [ManifestWebDesign/angular-gridster#254]
A question, really.  I'm still somewhat new to angular, so maybe I'm missing something, but I want to access the current column and row heights, in order to resize some grid items appropriately.  How do I access the current row and column height, or more generally, access the gridster item.  I can look at the gridsterOpts, but if it the column width is set to "auto", that won't help.

**Comment by danomatic** [comment]
If you are looking to access the pixel sizes of rows and columns, you can do so a few ways:

## 1
look at the gridster-item elements .with() and .height() using normal jQuery methods

## 2
listen for size change events and handle them:
https://github.com/ManifestWebDesign/angular-gridster#gridster-resized
Just put `console.log(arguments);` in that example callback to see what is available.

## 3
access those properties on the gridster controller directly using (only available in the latest release):
https://github.com/ManifestWebDesign/angular-gridster#controller-access
{{ gridster.curRowHeight }} {{ gridster.curColWidth }} are "private" properties that contain the calculated pixels.

Hopefully that helps!
