### ISSUE TITLE
Bower installation of 0.12.0 fails

### ISSUE THREAD

**Issue by gjungb** [ManifestWebDesign/angular-gridster#255]
Hi, when using ```bower install angular-gridster#0.12.0``` the release can not be found: ```ENORESTARGET No tag found that was able to satisfy 0.12.0```. It seems you need to add the release tag.

**Comment by mtraynham** [comment]
That's because 0.12.0 hasn't been released and there is no corresponding git tag.  Use:
`bower install angular-gridster#master`
 if you want to compile against the latest.

**Comment by danomatic** [comment]
I just created a release v0.12.0 based on master
