### ISSUE TITLE
v0.13.1 : On widget creation size-x and size-y is set at 1 column and 1 row size

### ISSUE THREAD

**Issue by Goochie** [ManifestWebDesign/angular-gridster#260]
Hi,

Was trying out v0.13.1 to compare the performance against @Malczewski  fork of gridster and i have come across the following issue - On creation all widgets size-x and size-y is set at 1 column and 1 row size. 

Even though i have explicitly set the x and y.

I am using attributes to set the x and y ......

      <li gridster-item
                size-x="gridLayout.sizeX"
                size-y="gridLayout.sizeY"
               ..................................................................

**Comment by danomatic** [comment]
is this still happening with latest master?  i'm not able to reproduce it.  The demo is set up just like your example and it honors the provided values.

**Comment by Goochie** [comment]
I have re looked at this issue as we are looking to upgrade to v0.13.2 and the issue would seem to be that the x and y properties are strongly typed now ie expect number / int and we was setting it to a string property of a json config loaded in, which was fine before but not so much now - although i now get the performance issues that were fixed by #245 patch - so may have to roll back
