### ISSUE TITLE
Serialization of widget state 

### ISSUE THREAD

**Issue by adaksuman** [ManifestWebDesign/angular-gridster#261]
Is it possible to serialize widget state for save and open later??

**Comment by danomatic** [comment]
Yes, but that is handled outside of the directive.  The directive is for rendering and updating values.  It uses Angular's two-way binding to update values, which you can then serialize and save/load as needed.  It doesn't dictate your external data model and workflow.

The app that drove me to create this does the following:

- creates "widget" objects and binds size and position values to gridster-items that are rendered using an ng-repeat inside of a gridster directive
- on drop or on resize, it loops through those objects and saves those values to a database via REST API
- when the page is reloaded, the array of objects is retrieved from the server and set in the scope
