### ISSUE TITLE
draggable.enabled not being picked up

### ISSUE THREAD

**Issue by nmacd** [ManifestWebDesign/angular-gridster#264]
This used to work in 11.7 but doesn't seem to work with the latest 13.2:

I am not using ng-repeat to populate my gridster items, but have them statically defined in the template, e.g.

```html
<div gridster="options">
    <ul>
        <li gridster-item row="0" col="0" size-x="3" size-y="2"></li>
    </ul>
</div>
```

If I set ``draggabled.enabled=false`` in my gridster options, this does not work and the gird item is still draggable. Setting  ``resizable.enabled=false`` does work, however.

If I use ``ng-repeat`` and populate from items in the scope, draggable works as expected.

Any ideas?

**Comment by danomatic** [comment]
Thanks for reporting this.  Current master fixes this issue.  There will be a new release soon.
