### ISSUE TITLE
preventing dragging on click

### ISSUE THREAD

**Issue by amarkitanis** [ManifestWebDesign/angular-gridster#267]
I dont think this is an issue per se but I'm not sure how it can be accomplished. 

When you click-to-drag on on a gridster item  it automatically increases the height of the entire container. 

This is desirable behaviour when you want to move but not desirable when you're about to click on something within that item. Clicking on an element inside a gridster item has the effect of starting a drag. Can this be somehow caught and disabled?

I found this thread: http://stackoverflow.com/questions/14301026/how-do-i-avoid-a-click-event-firing-after-dragging-a-gridster-js-widget-with-cli/25431791#25431791

but this solves it in a jquery manner and I'm not sure what ui.$player is.

**Comment by amergin** [comment]
As the documentation states, set up a `handle` by supplying a selector to which elements drag events should be bound to. For instance, in a dashboard application each item could have a header div to which the drag functionality is bound to, and nowhere else in that item.

```
    draggable: {
       handle: '.my-class', // optional selector
       ...
    }
```

**Comment by amarkitanis** [comment]
this is perfect, can you have multiple handles or only one?

**Comment by amarkitanis** [comment]
this is perfect - thank you!

**Comment by amarkitanis** [comment]
I have used handle:'.my-class' where this class is only attached onto the header of each widget. 

However I still find cases where I can drag the widget in random places e.g inside a td in a table. 

None of those td's has a class called '.my-class' attached to it.

**Comment by amergin** [comment]
Perhaps when https://github.com/ManifestWebDesign/angular-gridster/pull/274 merges it'll solve your problem?

**Comment by danomatic** [comment]
@amarkitanis, i think it's a race condition where the drag handle is created after the draggable is initialized.  I believe #277 covers that issue.
