### ISSUE TITLE
Wrong mobileMode detecting if gridster is hidden on initialization

### ISSUE THREAD

**Issue by huston007** [ManifestWebDesign/angular-gridster#270]
Version 13.2.
If gridster container have `display: none` on initialization, gridster initializing in mobile mode and staying in it when container becomes visible. Mobile mode stays turned on until first resize.

First time mobileMode detecting returns 'true' because `$elem[0].offsetWidth` is zero for hidden block children, like demonstrated here: http://jsfiddle.net/4weysLa1/

It not reproducing in 0.11.7, because there are a watch for `$elem[0].offsetWidth || parseInt($elem.css('width'), 10);`, which toggles mobileMode when gridster becomes visible, but now this watch working only in some conditions.

**Comment by huston007** [comment]
I'm using a workaround - triggering resize events manually when element.offsetWidth changes, but gridster onResize handler have 100ms debounce, so sometimes mobile mode is visible for small time when grid opening

**Comment by danomatic** [comment]
the latest commit adds some explicit checking for the gridster element being hidden.  my tests with ng-show and ng-hide work well.

**Comment by huston007** [comment]
@danomatic Thanks!
