### ISSUE TITLE
Cannot read property 'splice' of undefined at window.removeResizeListener

### ISSUE THREAD

**Issue by patroner** [ManifestWebDesign/angular-gridster#276]
On scope destroy, it's fired function window.removeResizeListener defined in detect-element-resize.js.

It shouldn't be triggered beacuse function window.addResizeListener wasn't fired.

if (typeof $elem.resize === 'function') {
	$elem.resize(onResize);
} else if (typeof window.addResizeListener === 'function') {
	window.addResizeListener($elem[0], onResize);
} 

If first condition is true, function addResizeListener isn't called, __resizeListeners__ are not added,  so on scope destroy removeResizeListener shouldn't be called.

**Comment by danomatic** [comment]
I think this is fixed in latest master.  Can you confirm?

**Comment by patroner** [comment]
Yes, it works correctly in 0.13.3. Thanks :)
