### ISSUE TITLE
Widget added to dashboard demo isn't draggable

### ISSUE THREAD

**Issue by crowdconnected** [ManifestWebDesign/angular-gridster#278]
Widgets added dynamically to the dashboard demo aren't draggable. The same behaviour is observed when in our code we add an item into an already rendered draggable grid: the new item renders, but isn't draggable.

**Comment by KapuzenSohn** [comment]
I have the same Problem. After I click on a Edge of an item I can drag it around.

**Comment by danomatic** [comment]
Fixed in the release today
