### ISSUE TITLE
Async Items Loading

### ISSUE THREAD

**Issue by morious** [ManifestWebDesign/angular-gridster#279]
Hi,
I have an issue where items are not draggable when they are populated on the scope after the application loaded. Ex. loading items from a server.
Did anyone run into a similar issue?

Thanks!

**Comment by danomatic** [comment]
Fixed in release today

**Comment by morious** [comment]
Thanks! It works now.

**Comment by GGeorgi** [comment]
Hi I have same problem but when setting gridsterOpt in html as attribute
here is plunker example: https://plnkr.co/edit/LheKiT?p=preview

Thanks
