### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Ledragon** [ManifestWebDesign/angular-gridster#282]
Hi,
First of all, big thanks for the project, it is great.
Second, I would like to know if there is any changelog somewhere. In particular, I would be interested to know about the breaking changes between 0.11 and 0.13, as I am thinking to migrate from one to the other.
Thanks in advance!

**Comment by prochafilho** [comment]
+1 - I am trying to switch from 0.11 to 0.13 unsuccessfully.

**Comment by danomatic** [comment]
The closest is here:
https://github.com/ManifestWebDesign/angular-gridster/releases

We try to follow semver, but I may have deviated a little.  The idea is that "release" (the last segment) increments are generally not breaking changes, but "minor" and "major" increments could have breaking changes.
