### ISSUE TITLE
Gridster with on-click Elements

### ISSUE THREAD

**Issue by griessbreilp** [ManifestWebDesign/angular-gridster#291]
Hello,
i want to build a customisable navigation.
So far everything works pretty fine, my only problem is, i cannot drag the elements, when they have a clickable html element inside, with width and height of 100%.

Here is a little plnkr to show my problem:
http://plnkr.co/edit/qqprcY?p=preview

I can resize and all, but not sort or drag them.

**Comment by griessbreilp** [comment]
I solved my problem.
I don't want to drag and resize my buttons all the time, just when the user is in the Edit Mode. So what i did was simply, i watch if the "Edit-Mode" variable changes to true, and if this happens, i append my button with an <div class="dragMe"></div> with the style:
.dragMe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

and tell gridster that .dragMe is the drag Handle.

When i leave the EditMode i simply $('.dragMe').remove(); the elements.

**Comment by danomatic** [comment]
Yeah there is specific code to avoid drag events for inputs and buttons.  This is a fairly special use case, so I'm glad you were able to work it out.
