### ISSUE TITLE
gridster-item-initialized is not triggered

### ISSUE THREAD

**Issue by k1ng440** [ManifestWebDesign/angular-gridster#293]
Hello, i am trying to catch gridster-item-initialized buts its not being triggered

            $scope.$on('gridster-item-initialized', function(item) {
                console.log(item);
            });

**Comment by prochafilho** [comment]
I am having the same issue

**Comment by k1ng440** [comment]
i have solved the issue using a directive

```
<li class="widget" gridster-item="widgetsMap" id="{{widget.type}}" ng-repeat="widget in widgets" ng-if="widget.active">
                <i resize-chart="widget.chartConfig" resize-chart-from="gridsterItem"></i>
<li>
```

```
 .directive('resizeChart', function ($timeout, $interval) {
            function link($scope) {
                function resizeChart() {
                    $scope.resizeChart.size.height = $scope.resizeChartFrom.$element[0].clientHeight - 100;
                    $scope.$emit('reflow.chart');
                }

                var wasMoving = false;
                $interval(function() {
                    if ($scope.resizeChartFrom.isMoving() === true) {
                        wasMoving = true;
                        resizeChart();
                    } else if (wasMoving === true) {
                        $timeout(resizeChart, 200);
                        wasMoving = false;
                    }
                }, 300);

                $timeout(resizeChart, 200);
            }

            return {
                restrict: 'A',
                scope: {
                    resizeChart: '=resizeChart',
                    resizeChartFrom: '=resizeChartFrom'
                },
                link: link
            };
        })
```

hope its helps

**Comment by prochafilho** [comment]
Thank you

**Comment by peibol16** [comment]
Same problem for me

**Comment by prochafilho** [comment]
What version are you using?

**Comment by danomatic** [comment]
gridster-item-initialized is only broadcast within the scope of the gridster item itself.  perhaps you are looking for it in another scope?

**Comment by ronnyek** [comment]
I realize its not a bug, is there an example of what this looks like? I'd like to also get some sort of event once a gridster item is intiialized

**Comment by brendanoffer** [comment]
gridster-item-initialized is not working for me. I have it placed directly next to my watcher for gridster-item-resize, which does work.  They are both inside the gridster elements scope. 

Any suggestions / am I doing anything drastically wrong?

**Comment by pihomeserver** [comment]
+1 for an example how to get the gridster event fired (and catched)

**Comment by Moulde** [comment]
@brendanoffer Do you have an example? Where do you listen for the resize and initialized events?

**Comment by woutrbe** [comment]
Same issue here, I'm listening to the `gridster-item-initialized` event in the same scope as where I initialise gridster, can confirm it's never fired.

**Comment by abeytom** [comment]
The event is broadcasted before the listener is initialized.

**Comment by brendanoffer** [comment]
I ended up making a directive to watch for the initialization. This is working for me now.

```
angular.module('myApp').directive('initalize-watcher', function () {
    return {
        restrict: 'AE',
        link: function (scope) {
            scope.$on('gridster-item-initialized', function (event, item) {
                // Do Something
            });
        }
    };
});
```

HTML
```
<ul>
    <li initialize-watcher 
                ng-repeat="item in page.items">
    </li>
</ul>
```
