### ISSUE TITLE
Handler on scrolling

### ISSUE THREAD

**Issue by prochafilho** [ManifestWebDesign/angular-gridster#294]
![nimbus-image-1434989515934](https://cloud.githubusercontent.com/assets/5936212/8286501/8fa39234-18cf-11e5-9933-7f24dd618ea1.png)

If a widget has been resized to a size smaller than the original size the resize handle will be static instead on being on bottom of the widget. Any thoughts?

**Comment by k1ng440** [comment]
i had similar issue, i have fixed it with css like this
```
height: calc(100% - 100px)
```
