### ISSUE TITLE
angular-chart.js not work inside gridsterItem

### ISSUE THREAD

**Issue by reidlai** [ManifestWebDesign/angular-gridster#297]
I tried to embed angular-chart.js inside gridsterItem but seems only how serious label without chart.  When I pull it out and display outside <ul gridster></ul>, everything works fine.  How can I make the chart shown inside gridsterItem?

**Comment by danomatic** [comment]
You probably need to make the chart element `position:absolute` with `top: 0; bottom: 0; left: 0; right: 0;`
