### ISSUE TITLE
resizable-handler not on top of content

### ISSUE THREAD

**Issue by RonB** [ManifestWebDesign/angular-gridster#298]
In some cases the resize-handlers are covered with content of the widget. I have a videogular video in a widget and the controls of the video cover the resize handlers sw, s and se. I have added

    .gridster-item-resizable-handler {
        z-index: 9999;
    }

to my css and its working fine now. Should this be the default for this class?

**Comment by danomatic** [comment]
Yeah a z-index would be good was 9999 required in your case or would a value of 1 or 5 do the trick?

**Comment by danomatic** [comment]
Added a z-index of 5 in 40135f4d5f12796519fcb9b7976879c210573459

**Comment by RonB** [comment]
Unfortunately its unpredictable which z index content will use so 9999 was required for me.
