### ISSUE TITLE
[Question] Adding new widgets "draggable"

### ISSUE THREAD

**Issue by TheBoef** [ManifestWebDesign/angular-gridster#30]
Is it possible to create a draggable list that can drag widgets too the Gridster grid and interact with the gridster?

Right now I got it working to drag an item in the gridster, but I wonder if it's possible to also let my draggable interact with gridster like its already a 'widget' inside the grid.

I hope my question is clear and anyone can give me an answer :)

**Comment by maheshbabubokkisam** [comment]
Hi do you have any example for this
