### ISSUE TITLE
Too slow while adding an item to the grid

### ISSUE THREAD

**Issue by koolshams** [ManifestWebDesign/angular-gridster#324]
Good plugin.

Looks like there is a NxMxNxM scanning when adding new item to the grid. So browser hangs for some seconds. I made some optimization, so  it reduced.  But may cause regression issues. Are you guys have any plan for this. 

Thanks

**Comment by MaiGhoneim** [comment]
the same Issue happening with me, is there any fix for this

**Comment by koolshams** [comment]
Created a pull request. Seems all tests are passed. Just give a try
https://github.com/ManifestWebDesign/angular-gridster/pull/326

**Comment by koolshams** [comment]
Please give a try with my fork. 
https://github.com/koolshams/angular-gridster/tree/koolshams-performance-fix

**Comment by koolshams** [comment]
Looks like there are similar issues reported. So closing this issue
