### ISSUE TITLE
Make tiles not resizeable but draggable

### ISSUE THREAD

**Issue by magx2** [ManifestWebDesign/angular-gridster#339]
Hi, 

I'm trying to make my tiles **not** resizeable and draggable.

To do this I've added code:

	angular.module(..., ...)
		.config(function (gridsterConfig) {
			gridsterConfig.resizable = {enabled: false};
			//gridsterConfig.draggable = {enabled: true};
		});

What is odd changing ```resizable``` to ```false``` also block dragging elements. Even setting ```draggable``` to ```true``` does not help (in the comment above).

Is this a bug or I'm making some stupid mistake?

**Comment by tangorri** [comment]
By default draggable is set to false remove comment please :)

**Comment by magx2** [comment]
It does not help. With this code:

        gridsterConfig.resizable = {enabled: false};
        gridsterConfig.draggable = {enabled: true};

I still can not move tiles

**Comment by TimGeerts** [comment]
Just ran into this as well, apparently setting resizable to false, still needs you to set a "handles" object as the javascript requires it.
```javascript
gridsterConfig.resizable = {
  enabled: false,
  handles: [],
};
```
That works for me.
(Sorry, I guess I could make a pull request and change the logic to stop looking for the "handles" property when using "enabled: false", but, I'm a github noob...)

**Comment by magx2** [comment]
Thanks for refreshing. Right now I changed my requirements and now users can resize tiles ;), so probably I wont need it, but anyway thanks :).
