### ISSUE TITLE
Deleting an item kill the events handlers

### ISSUE THREAD

**Issue by pihomeserver** [ManifestWebDesign/angular-gridster#351]
I have a grid with items. Each item has a top menu with inside each :
```
<i class="widget-draggable fa fa-arrows"></i>
```
All works fine until i delete one of the items like this :
```
  $scope.deleteWidget = function(widget) {
    $scope.dashboard.widgets = $scope.dashboard.widgets.filter(function( obj ) {
        return obj !== widget;
    });
  }
```
Then all other items can not be drag or resized.
If i add a new widget then events work great on this item only but still not on others. By the way the widget is added at the first place of the grid, not the first free place
If i refresh the grid/page then events come back to all items.

I do not know how to debug that as no error are displayed in the console
Any help is welcome

**Comment by GoodCoding** [comment]
I think, the problem that the grid items are bound to events with the existing array of widgets.
If I'm not totally wrong, the filter function returns a new array and not the original one.
Try to splice the item you wish to remove from the array.

**Comment by pihomeserver** [comment]
@GoodCoding thanks for the tip. I tried but still got the issue. But thanks to you i was able find the reason : after the delete is broadcast an event called $destroy and it's the reason why events stop working as soon as i comment the line it works
