### ISSUE TITLE
Does this work well in latest browsers with latest version of gridster?

### ISSUE THREAD

**Issue by erslater** [ManifestWebDesign/angular-gridster#357]
This is exactly what I am looking for.  Does it function ok in a production environment on the latest browsers?  The reason I ask is that it doesnt look like it is being actively maintained any longer (Perhaps I am wrong.  I just see lots of issues but no comments or updates from the owner).

**Comment by TheBosZ** [comment]
It works very well for all modern browsers. It even supports back to IE8. If you're worried about how it works in a browser, try [the demo](https://rawgit.com/ManifestWebDesign/angular-gridster/master/index.html).

The project isn't abandoned and is the center of one of our main products. We've been busy with other things, and unfortunately, that means less communication on Github.

I'm going to close your issue, please reopen if you run into any issues.
