### ISSUE TITLE
How to call methods outside directive controller "GridsterCtrl"?

### ISSUE THREAD

**Issue by intobrackets** [ManifestWebDesign/angular-gridster#37]
Hello,

is it possible to call methods of the gridster outside "GridsterCtrl" ? (from other service)
for example: i wanna to call these methods:  toJSON, getColumns, ...

THX.

**Comment by mconner** [comment]
The issue I'm having is that while the data is bound, other information about the grid is not.  I'd like access to the current width/height, current row width and column height.  This information is in the controller.
