### ISSUE TITLE
Gridster + Chart.js

### ISSUE THREAD

**Issue by JobaDiniz** [ManifestWebDesign/angular-gridster#385]
I'm using Chart.js angular version: http://jtblin.github.io/angular-chart.js
**Problem 1**: UI is messy when combining gridster and chart.js because chart changes element height accordingly to its width.

![resize-handle-2](https://cloud.githubusercontent.com/assets/165290/13725108/e9d03970-e876-11e5-8a87-a15aec16ccd8.png)

**Problem 2** *(not related to chartjs)*: the green box height is small, but the resize handle shows below it:

![resize-handle-1](https://cloud.githubusercontent.com/assets/165290/13725109/fa743f4c-e876-11e5-99a8-5e378d881383.png)

Any insights on how to fix this?

**Comment by axar** [comment]
set the height and width of the chart based on the gridster item's width and height which can be acquired by a method. Reapply the width and height then redraw on gridster re-size, item re-size and item re-size transition end.

**Comment by JobaDiniz** [comment]
`gridster-item-resized` is triggered on every mouse move, isn't there an event that only triggers when the resize is completely done, that is, when the user let go *drag handle*?

**Comment by axar** [comment]
gridster-item-transition-end

**Comment by axar** [comment]
The resize is called on col and row change. So it's not too bad unless you have many rows and cols.

**Comment by JobaDiniz** [comment]
> set the height and width of the chart based on the gridster item's width and height which can be acquired by a method. Reapply the width and height then redraw on gridster re-size, item re-size and item re-size transition end.

This helped, but the only way to make it work with resizing was to remove `<canvas>` completely from DOM and add it again with the new width/height.

Thanks.
