### ISSUE TITLE
angular2 & gridster

### ISSUE THREAD

**Issue by bona1337** [ManifestWebDesign/angular-gridster#396]
I am trying to integrate gridster into angular2..... but too many issues until now... does anyone have a solution yet?

**Comment by saharza** [comment]
i was struggling with that issue to, in the end i was able to do "side by side" angular-gridster (1.5) with angular 2.0 (beta.11) but in pure javascript (no typescript).

**Comment by BBlume** [comment]
pretty dirty but working! there should be a better solution! hopefully something shows up soon...

**Comment by plgregoire** [comment]
@bona1337 
I would be interested to know what you have tried. Have you tried to use ngUpgrade or have you tried to rewrite it in typescript ?

**Comment by saharza** [comment]
I useג ngUpgrade.

**Comment by bona1337** [comment]
I tried to rewrite with typescript.

**Comment by aklokov** [comment]
@bona1337 Hi, do you have any progress in rewriting this lib with typescript? and running it on angular2? Thanks!!!

**Comment by bona1337** [comment]
@aklokov check this out....
https://github.com/BTMorton/angular2-grid
I guess thats what everybody is looking for.... 👍

**Comment by rajesh-kanakabandi** [comment]
Looks like there are a couple of other options amongst which angular2gridster could be a good one'
https://github.com/swiety85/angular2gridster 

regards,

**Comment by skol-pro** [comment]
@rajesh-kanakabandi That's a really bad implementation, at least really uncomplete... :-(

**Comment by rajesh-kanakabandi** [comment]
@skol-pro I'm not sure what your need is. just mentioned that there are other options too. no harm in checking them out.
