### ISSUE TITLE
Gridster with NVD3

### ISSUE THREAD

**Issue by whittssg** [ManifestWebDesign/angular-gridster#401]
Hello, I am trying to use gridster with NVD3 charts but i am running into a few issues..

I currently have to set NVD3 charts to have a bottom margin of 75 to fit into the Gridster panles.. This works well in none mobile views.. (although in dev mode i can see that the nvd3 passes the panel by quite alot which is why i have to use such a huge margin). When i reduce the screen width to mobile size everything resizes as expected apart from NVD3.. In mobile view the margin is too big and causes the chart to be cut off. Why would NVD3 (a child of gridster) need a bottom margin of 75 in normal mode so that it doesnt get cut off but not need it in mobile view?

Question 2.. i tried to get around this by using  $scope.$on('gridster-mobile-changed', function (gridster) and the altering the margin myself but it doesnt seem to be able to detect the change in margin (i check to see what the current margin is and change accordingly)... Is there a way to know if its going into mobile view rather than either or?

Thanks

**Comment by dekkofilms** [comment]
@whittssg did you ever arrive to a solution on this issue?
