### ISSUE TITLE
Dragging stopped working since 0.13.6 update

### ISSUE THREAD

**Issue by fenix2222** [ManifestWebDesign/angular-gridster#409]
Since we updated library from 0.13.5 to 0.13.6 dragging for all widgets stopped working

**Comment by danomatic** [comment]
Can you check the most recent version?  I think there was an issue with the drag if the click event occurred on a child element of a elements matching the `handle` selector.

**Comment by mtraynham** [comment]
I tried with the latest.  It does let you drag the "handle" dom node, but children of the handle prevent dragging, which is different from 0.13.5.

**Comment by mportuga** [comment]
@danomatic Should you close this issue since it has been resolved?
