### ISSUE TITLE
"main" section in bower.json missing file: angular-gridster.min.js

### ISSUE THREAD

**Issue by leozcx** [ManifestWebDesign/angular-gridster#410]
The doc says "dist/angular-gridster.min.js" should be included, but this file is not appeared in  "main" section in bower.json, so some build tool like "wiredev" will fail to inject this file.

**Comment by danomatic** [comment]
This is the current main.  Doesn't that work?
```
"main": ["src/angular-gridster.js", "dist/angular-gridster.min.css"],
```

**Comment by zcx8532** [comment]
well, it works, but using "src/angular-gridster.js" which is not minified; since css file is using the dist one, why not keep it consistent.

**Comment by danomatic** [comment]
The CSS is compiled from scss, so there is only a minified version. I tend
to use the non minified JS in my projects and then handle concatenation and
minification when I build my project.  That way I can see line numbers and
debug better when I develop.  But if you don't do it that way, you can
always use the minified JS.  You aren't forced to use the src JS.

On Wednesday, May 25, 2016, Leo <notifications@github.com> wrote:

> well, it works, but using "src/angular-gridster.js" which is not minified;
> since css file is using the dist one, why not keep �it consistent.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ManifestWebDesign/angular-gridster/issues/410#issuecomment-221752664>
>


-- 

*Dan Blaisdell*
*Founder and Owner*
800.513.4814
503.382.9273 (Cell)
manifestwebdesign.com / manifestinsights.com
