### ISSUE TITLE
dragging on nested child element when using drag handle

### ISSUE THREAD

**Issue by paradite** [ManifestWebDesign/angular-gridster#419]
Hi,
I am trying to use the custom drag handler and initiate the dragging when the event is from a child element nested down below a few `div`s, however, I found out that the matching failed.

Digging into the source code, I found the following lines:
https://github.com/ManifestWebDesign/angular-gridster/blame/master/src/angular-gridster.js#L1379

								for (var p = 0; p < 20; ++p) {
									var parent = e.target.parentNode;
									if (parent === $el[0]) {
										break;
									}
									if (parent === handle) {
										match = true;
										break outerloop;
									}
								}

I think what this code is trying to achieve is recursively matching the element's parent, but in reality, it is only matching the same "first parent" of the element again and again, is this the cause of my issue?

**Comment by paradite** [comment]
Here is a fix that I implemented, which solved the issue for me:

								var parent = e.target;
								for (var p = 0; p < 20; ++p) {
									parent = parent.parentNode;
									if (parent && parent === $el[0]) {
										break;
									}
									if (parent && parent === handle) {
										match = true;
										break outerloop;
									}
								}

Let me know if you want a PR for this.

**Comment by GerritK** [comment]
same problem here. please PR it.

**Comment by DooMMasteR** [comment]
definetly
please create a PR for it

**Comment by danomatic** [comment]
Should be fixed in latest release!  Thank you!
