### ISSUE TITLE
How to catch "Unable to place item!" exception?

### ISSUE THREAD

**Issue by jcubic** [ManifestWebDesign/angular-gridster#445]
I would like to intercept the exception do some action when it occur, is it possible?

**Comment by jcubic** [comment]
Found it using this code:
```javascript
  .factory('$exceptionHandler', ['$log', function($log) {
    return function(exception, cause) {
      $log.error(exception, cause);
      showError(exception.message);
    };
  }]);
```

**Comment by PythonDevOp** [comment]
@jcubic where did you use this code? Perhaps do you have an example of where to place it and how it is used? I too am struggling to deal with the 'unable to place item' exception, and any further insight would be helpful.

**Comment by jcubic** [comment]
You can add this code to main module:
```
var app = angular.module('app', []);
app.factory('$exceptionHandler', ['$log', function($log) {
    return function(exception, cause) {
    };
});
```

**Comment by PythonDevOp** [comment]
Ah, ok I understand now. One typo in your code -> there should be a closing bracket at the end like so `}])`. Thanks for clarifying.
