### ISSUE TITLE
Broadcast "gridster-loaded" event for use with nested directives

### ISSUE THREAD

**Issue by alsoscotland** [ManifestWebDesign/angular-gridster#51]
I have a use-case that may prove useful to other angular-gridster users.  

I have a chart-drawing directive which is nested inside a gridster directive and is dynamically drawn to fill the available size of the gridster item.

Currently, I do not have a very straightforward way to know (from the perspective of my directive's scope) when the gridster element has been assigned its width and height.
So I have a race condition where sometimes the chart is drawn correctly and sometimes it is drawn prior to gridster finishing its width-calc.

It would be useful for this case if the gridster-directive would broadcast a "gridster-loaded" event so that a user can have explicit knowledge that the width has been calculated.  

``` js
scope.$broadcast('gridster-loaded');
```

could be added in the same timeout inside the directive's compile:post function which adds the gridster-loaded class.  
[compile post timeout gridster.js #L592-L595](https://github.com/ManifestWebDesign/angular-gridster/blob/master/src/angular-gridster.js#L592-L595)

Or it could be placed in the end of the redraw function in the controller

**Comment by achandel** [comment]
+1
