### ISSUE TITLE
Resize of element does not trigger resize()

### ISSUE THREAD

**Issue by frapontillo** [ManifestWebDesign/angular-gridster#52]
When resizing the parent `gridster` containing the items, no call to `resize()` will be triggered since the only check is made on the [window size](https://github.com/ManifestWebDesign/angular-gridster/blob/master/src/angular-gridster.js#L574):

```
angular.element(window).on('resize', function(){
    resize();
    scope.$apply();
});
```

Since dynamic layouts are very common, could you consider using something like [**jquery-resize**](https://github.com/cowboy/jquery-resize) to bind to the `gridster` instead?

**Comment by gauravsoni1** [comment]
So is this been implemented ? cause the jQuery resize event is still not firing..
