### ISSUE TITLE
add element to gridster via drag-and-drop

### ISSUE THREAD

**Issue by milevskiy-r** [ManifestWebDesign/angular-gridster#69]
Hello,
In my project, i need to provide the ability to create an element withing gridster via drag-and-drop from outside the gridster area. It would be great to hear recomendations about whats a better way to do this. Currently i am using angular-dragdrop, but i have a weird feeling its not a best way
Thank you for your time

**Comment by WigglesTehPro** [comment]
Is there any update on anyone getting this to work?
