### ISSUE TITLE
Gridster Item Height Issues when Dynamically Adding Content

### ISSUE THREAD

**Issue by dtothefp** [ManifestWebDesign/angular-gridster#70]
First off, thanks for the great module.  I've been toying around with it a lot at work and it is exactly what I need for the product we are building.  One problem I'm running into is we are dynamically adding module content to a module editor page.  This module content is what I want to be a gridster draggable/resizable item.  I've toyed around how to add the content either via a directive, ng-include, or ui-view using ui router.  In every case the gridster resizable container does not adjust to the height of the content.  I'm wondering if I have to specify a sizeY property on the fly for every item or if there is a way to re-initialize the gridster resizable JS after adding the module.  I'm assuming this has something to do with directive element size not being fully defined in the link function, as I have run into this problem many times in the past and not found a fix for it.  An example of the code is below and I've attached a screenshot:

```
  <div class="wrapper row" gridster="gridsterOpts">
    <div ng-repeat="template in templates" gridster-item="template">
      <div ng-if=" template.name == 'share_photo' " ui-view="share_photo">
      </div>
      <div ng-if=" template.name == 'share_video' " ui-view="share_video">
      </div>
    </div>
  </div>
```

In the screenshot you can also see if I do not adjust the resizable container to contain the content after it is rendered to the page, the gridster item below it will push up through the content to the bottom of the resizable box.  I tried making a directive with a $timeout to adjust the gridster-item height to the content height, but then the positioning of the gridster items below reference from the initial position and push up into the above content
![screen shot 2014-05-19 at 1 57 58 pm](https://cloud.githubusercontent.com/assets/4656726/3017909/5f010fb0-df7f-11e3-9870-cec36e7344c6.png)

**Comment by nikhil-venkat** [comment]
Is there a workaround for this problem ?
