### ISSUE TITLE
Serialization Example

### ISSUE THREAD

**Issue by Linell** [ManifestWebDesign/angular-gridster#77]
Is it possible to serialize the entire grid into a JSON object?

In the gridster.js library, the given example is simply `gridster.serialize();`. Is there something that simple with angular-gridster?

This would be something good to have easily visible in the README.

**Comment by sureshkoduri** [comment]
I also struck here. Please help with code example

**Comment by saharza** [comment]
this is my code in the main controller that containing the gridster:
        
        $scope.saveDashboardLayout = function saveDashboardLayout() {
            sessionStorage.userDashboardLayout = angular.toJson($scope.standardItems);
        };

        $scope.loadDashboardLayout = function loadDashboardLayout(){
            $scope.standardItems = angular.fromJson(sessionStorage.userDashboardLayout);
        };

where the - $scope.standardItems - is the array of widgets that the gridster is doing ng-repeat on them:
    $scope.standardItems = [{
                name: 'Widget2',
                sizeX: 3,
                sizeY: 2,
                row: 2,
                col: 4
            }, {}, {}, {}....]

**Comment by DodgersDev** [comment]
This code:
`    $scope.saveDashboardLayout = function saveDashboardLayout() {
        sessionStorage.userDashboardLayout = angular.toJson($scope.standardItems);
    };

    $scope.loadDashboardLayout = function loadDashboardLayout(){
        $scope.standardItems = angular.fromJson(sessionStorage.userDashboardLayout);
    };`

Return: [object Object],[object Object].....
Why not return this: $scope.standardItems = [{
name: 'Widget2',
sizeX: 3,
sizeY: 2,
row: 2,
col: 4
}, {}, {}, {}....]

Where is the problem?
