### ISSUE TITLE
Resizing widget beyond boundaries causes overlap

### ISSUE THREAD

**Issue by jverghese** [ManifestWebDesign/angular-gridster#91]
On latest master, if you resize a widget beyond the edges, the resized widget ends up overlapping with the existing widget with a proper reflow. See screenshot below.

![overlappinggridsteritem](https://cloud.githubusercontent.com/assets/635679/3518769/769d824c-0708-11e4-8143-82dc5f6a28a8.png)

**Comment by SwapnaLReddy0405** [comment]
I still see overlapping issue with latest(0.13.5) version. This is when adding widgets/items to dashboard.
Please provide the fix, as we are unable to resolve this issue.

**Comment by lucasscarduelli** [comment]
This bug is solved? I have this problem when set maxRows to the gridster.
